global:
  
  argoSourceRepoURL: https://github.com/Howard-Luo/non-olm-cp4d-gitops-530.git

  operatorNS: gitops-operator
  instanceNS: gitops-instance
  licensingNS: gitops-licensing
  appSuffix: gitops
  fileStorageClass: ocs-external-storagecluster-cephfs
  blockStorageClass: ocs-external-storagecluster-ceph-rbd
  imagePullPrefix: icr.io
  imagePullSecret: ibm-entitlement-key
  argocdNS: openshift-gitops
  helmRepoURL: https://howard-luo.github.io/non-olm-cp4d-gitops-530/repos
  installConfigImageDigest: "sha256:53f6b5487363e47f00ae3879e861062a460df0f6ffab57ea077da34a1b678563"

  cpd-platform-cluster:
    chart: cpd-platform-cluster-scoped
    version: 5.3.0+20251122.143747.124
  cs-cluster:
    chart: ibm-common-service-operator-cluster-scoped
    version: 4.16.0+20251107.123839.0
  im-cluster:
    chart: ibm-iam-operator-cluster-scoped
    version: 4.15.0+20251111.110850.0
  postgresql-cluster:
    chart: postgresql-cluster-scoped
    version: 5.30.0+20251030.094351.108
  zen-cluster:
    chart: zen-cluster-scoped
    version: 6.3.0+20251122.162557.333
  ibm-licensing-cluster:
    chart: ibm-license-service-cluster-scoped
    version: 4.2.16+20250528.101036.0

  cs:
    chart: ibm-common-service-operator
    version: 4.16.0+20251107.123839.0
  im:
    chart: ibm-iam-operator
    version: 4.15.0+20251111.110850.0
  postgresql:
    chart: postgresql
    version: 5.30.0+20251030.094351.108
  zen:
    chart: zen
    version: 6.3.0+20251120.181620.331
  cpd-platform:
    chart: cpd-platform
    version: 5.3.0+20251122.143747.124


## "Repository": "cp.icr.io/cp/cpd/olm-utils-premium-v4"
## sha256:53f6b5487363e47f00ae3879e861062a460df0f6ffab57ea077da34a1b678563