resources:
  - ccs-cluster.yaml
  - ccs.yaml
  - datarefinery-cluster.yaml
  - datarefinery.yaml
  - opensearch-cluster.yaml
  - opensearch.yaml
  - watsonx-ai-cluster.yaml
  - watsonx-ai.yaml
  - watsonx-ai-ifm-cluster.yaml
  - watsonx-ai-ifm.yaml
  - wml-cluster.yaml
  - wml.yaml
  - ws-runtimes-cluster.yaml
  - ws-runtimes.yaml
  - ws-cluster.yaml
  - ws.yaml
  - redis-cp-cluster.yaml
  - redis-cp.yaml
  - watsonx-orchestrate-cluster.yaml
  - watsonx-orchestrate.yaml