apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-config-gitops
  namespace: openshift-gitops
  labels:
    scope: namespace
    product: software-hub
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://github.com/Howard-Luo/non-olm-cp4d-gitops-530/repos
    targetRevision: ${platform-config-version}
    chart: ${platform-config-chart}
    helm:
      valuesObject:
        global:
          licenseAccept: true
          releaseVersion: 5.2.0
          operatorNamespace: gitops-operator
          instanceNamespace: gitops-instance
          imagePullPrefix: icr.io
          imagePullSecret: ibm-entitlement-key
          installConfigImageDigest: sha256:f97f1b364a27acfe08b1c80d9ce91c25f07e6005a7ba821abf164c8e38925a04
          installConfigImageName: cpopen/cpd/olm-utils-v3
          components:
            - planning_analytics
            - cpd_platform
        commands:
          applyEntitlement:
            - entitlement: cpd-enterprise
              production: "false"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
