apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-config-gitops
  namespace: openshift-gitops
  labels:
    scope: namespace
    product: software-hub
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://howard-luo.github.io/non-olm-cp4d-gitops-530/repos
    targetRevision: ${platform-config-version}
    chart: ${platform-config-chart}
    helm:
      valuesObject:
        global:
          licenseAccept: true
          releaseVersion: 5.3.0
          operatorNamespace: gitops-operator
          instanceNamespace: gitops-instance
          imagePullPrefix: icr.io
          imagePullSecret: ibm-entitlement-key
          installConfigImageDigest: sha256:53f6b5487363e47f00ae3879e861062a460df0f6ffab57ea077da34a1b678563
          installConfigImageName: cpopen/cpd/olm-utils-v4
          components:
            - planning_analytics
            - cpd_platform
        commands:
          applyEntitlement:
            - entitlement: cpd-enterprise
              production: "false"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
